name: ThreeFingers

shape_meta: &shape_meta
  # acceptable types: rgb, depth, low_dim
  obs:
    camera_rgb:
      shape: [3, 240, 320]
      type: rgb
    camera_depth:
      shape: [1, 240, 320]
      type: depth
    contact_force_z:
      shape: [3]
      type: low_dim
    ee_pose:
      shape: [3]
      type: low_dim
    ee_quat:
      shape: [4]
      type: low_dim
  action: 
    shape: [10]

dataset_path: &dataset_path data/dataset_H480W640_128.hdf5
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.isaaclab_image_runner.IsaacLabImageRunner
  dataset_path: *dataset_path
  shape_meta: *shape_meta
  task_name: Template-Threefingers-v0
  n_train: 0
  n_train_vis: 0
  train_start_idx: 0
  n_test: 10
  n_test_vis: 1
  test_start_seed: 100000
  # use python's eval function as resolver, single-quoted string as argument
  max_steps: 1200
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_obs_key: 'camera_rgb'
  fps: 20
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  tqdm_interval_sec: 1.0
  n_envs: 1
  enable_cameras: True
  headless: True
  device: ${training.device}
  depth_min: 0.3541673421859741
  depth_max: 0.46333277225494385
  depth_invert: False
  use_initial_image_obs_only: True
  observe_before_act_steps: ${policy.persistent_action.warmup_steps}
  binary_action_indices: ${policy.binary_action.indices}
  binary_action_low: ${policy.binary_action.low_value}
  binary_action_high: ${policy.binary_action.high_value}
  binary_action_threshold: ${policy.binary_action.threshold}
  quaternion_action_indices: ${task.dataset.action_quat_indices}
# evaluation at this config requires a 16 core 64GB instance.

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  action_preprocess: pos_quat
  action_pos_indices: [0, 1, 2]
  action_quat_indices: [3, 4, 5, 6]
  action_range_indices: [7, 8]
  normalize_action_quaternion: True
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  return_persistent_action_value: False
  persistent_action_indices: []
  persistent_action_window: 0
  persistent_action_reduce: mean
  binary_action_indices: []
  binary_action_low: -1.0
  binary_action_high: 1.0
  binary_action_threshold: 0.0
  depth_min: ${task.env_runner.depth_min}
  depth_max: ${task.env_runner.depth_max}
  depth_invert: ${task.env_runner.depth_invert}
  use_initial_image_obs_only: True
  use_cache: True
  seed: 42
  val_ratio: 0.05
